name: pycaret-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.11
  - pip
  - pip:
    - azureml-defaults
    - pycaret==3.3.2
    - numpy==1.25.2
    - featuretools==1.31.0
    - joblib==1.3.2